"""lot_model

Revision ID: 044833282c53
Revises: cea880a6b903
Create Date: 2026-03-06 23:31:53.308822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044833282c53'
down_revision: Union[str, Sequence[str], None] = 'cea880a6b903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_lots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_fill_id', sa.String(length=36), nullable=True),
    sa.Column('qty_opened', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('qty_closed', sa.Numeric(precision=38, scale=18), server_default='0', nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('entry_notional', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('collateral_asset', sa.Text(), nullable=True),
    sa.Column('leverage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_position_lots_position_id_positions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_fill_id'], ['trade_fills.id'], name=op.f('fk_position_lots_source_fill_id_trade_fills'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_lots'))
    )
    op.create_index(op.f('ix_position_lots_position_id'), 'position_lots', ['position_id'], unique=False)
    op.create_table('lot_allocations',
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('closing_fill_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('qty', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('realized_pnl_gross', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fee_cost', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fee_currency', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['closing_fill_id'], ['trade_fills.id'], name=op.f('fk_lot_allocations_closing_fill_id_trade_fills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['position_lots.id'], name=op.f('fk_lot_allocations_lot_id_position_lots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lot_id', 'closing_fill_id', name=op.f('pk_lot_allocations'))
    )
    op.create_index(op.f('ix_lot_allocations_closing_fill_id'), 'lot_allocations', ['closing_fill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_allocations_closing_fill_id'), table_name='lot_allocations')
    op.drop_table('lot_allocations')
    op.drop_index(op.f('ix_position_lots_position_id'), table_name='position_lots')
    op.drop_table('position_lots')
    # ### end Alembic commands ###
