"""margin_fields

Revision ID: cea880a6b903
Revises: fe2642c1d02d
Create Date: 2026-03-06 23:26:17.467234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea880a6b903'
down_revision: Union[str, Sequence[str], None] = 'fe2642c1d02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('margin_mode', sa.Text(), nullable=True))
    op.add_column('positions', sa.Column('leverage', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('positions', sa.Column('collateral_asset', sa.Text(), nullable=True))
    op.add_column('trade_fills', sa.Column('margin_mode', sa.Text(), nullable=True))
    op.add_column('trade_fills', sa.Column('leverage', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('trade_fills', sa.Column('collateral_asset', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_fills', 'collateral_asset')
    op.drop_column('trade_fills', 'leverage')
    op.drop_column('trade_fills', 'margin_mode')
    op.drop_column('positions', 'collateral_asset')
    op.drop_column('positions', 'leverage')
    op.drop_column('positions', 'margin_mode')
    # ### end Alembic commands ###
