"""init

Revision ID: fe2642c1d02d
Revises: 
Create Date: 2026-03-06 23:14:00.217503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2642c1d02d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('exchange', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='created', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bots'))
    )
    op.create_index(op.f('ix_bots_user_id'), 'bots', ['user_id'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exchange', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('contract_type', sa.Text(), nullable=False),
    sa.Column('base_asset', sa.Text(), nullable=True),
    sa.Column('quote_asset', sa.Text(), nullable=True),
    sa.Column('settle_asset', sa.Text(), nullable=True),
    sa.Column('contract_size', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('lot_size', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('price_precision', sa.Integer(), nullable=True),
    sa.Column('amount_precision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_instruments_exchange_symbol')
    )
    op.create_table('bot_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_bot_configs_bot_id_bots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_configs')),
    sa.UniqueConstraint('bot_id', 'version', name='uq_bot_configs_bot_id_version')
    )
    op.create_index(op.f('ix_bot_configs_bot_id'), 'bot_configs', ['bot_id'], unique=False)
    op.create_table('bot_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('config_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nomad_job_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_bot_runs_bot_id_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['config_id'], ['bot_configs.id'], name=op.f('fk_bot_runs_config_id_bot_configs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_runs'))
    )
    op.create_index(op.f('ix_bot_runs_bot_id'), 'bot_runs', ['bot_id'], unique=False)
    op.create_table('bot_capital_allocation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_run_id', sa.String(length=36), nullable=False),
    sa.Column('asset', sa.Text(), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('allocation_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('allocated_balance', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_run_id'], ['bot_runs.id'], name=op.f('fk_bot_capital_allocation_bot_run_id_bot_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_capital_allocation'))
    )
    op.create_index(op.f('ix_bot_capital_allocation_bot_run_id'), 'bot_capital_allocation', ['bot_run_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_run_id', sa.String(length=36), nullable=False),
    sa.Column('exchange', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('exchange_order_id', sa.Text(), nullable=True),
    sa.Column('client_order_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('position_mode', sa.Text(), nullable=True),
    sa.Column('position_side', sa.Text(), nullable=True),
    sa.Column('reduce_only', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('filled', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_run_id'], ['bot_runs.id'], name=op.f('fk_orders_bot_run_id_bot_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_bot_run_id'), 'orders', ['bot_run_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_run_id', sa.String(length=36), nullable=False),
    sa.Column('exchange', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('position_mode', sa.Text(), nullable=False),
    sa.Column('position_side', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_run_id'], ['bot_runs.id'], name=op.f('fk_positions_bot_run_id_bot_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('bot_run_id', 'symbol', 'position_mode', 'position_side', name='uq_positions_scope')
    )
    op.create_index(op.f('ix_positions_bot_run_id'), 'positions', ['bot_run_id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_run_id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('deal_direction', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('realized_pnl_gross', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fees_total', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('funding_total', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('realized_pnl_net', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('entry_avg_price_final', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('exit_avg_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('max_position_qty', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bot_run_id'], ['bot_runs.id'], name=op.f('fk_deals_bot_run_id_bot_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_deals_position_id_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_index(op.f('ix_deals_bot_run_id'), 'deals', ['bot_run_id'], unique=False)
    op.create_index(op.f('ix_deals_closed_at'), 'deals', ['closed_at'], unique=False)
    op.create_index(op.f('ix_deals_position_id'), 'deals', ['position_id'], unique=False)
    op.create_table('position_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('qty', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('open_notional', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('unrealized_pnl_gross', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('realized_pnl_gross', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fees_total', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('funding_total', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('margin_mode', sa.Text(), nullable=True),
    sa.Column('leverage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('initial_margin', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('maintenance_margin', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_position_snapshots_position_id_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_snapshots'))
    )
    op.create_index(op.f('ix_position_snapshots_position_id'), 'position_snapshots', ['position_id'], unique=False)
    op.create_table('trade_fills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_run_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('exchange', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('exchange_trade_id', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('position_side', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('qty', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('quote_qty', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fee_cost', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fee_currency', sa.Text(), nullable=True),
    sa.Column('is_maker', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bot_run_id'], ['bot_runs.id'], name=op.f('fk_trade_fills_bot_run_id_bot_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_trade_fills_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_fills')),
    sa.UniqueConstraint('exchange', 'symbol', 'exchange_trade_id', name='uq_trade_fills_exchange_symbol_trade_id')
    )
    op.create_index(op.f('ix_trade_fills_bot_run_id'), 'trade_fills', ['bot_run_id'], unique=False)
    op.create_table('deal_fills',
    sa.Column('deal_id', sa.String(length=36), nullable=False),
    sa.Column('fill_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_fills_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fill_id'], ['trade_fills.id'], name=op.f('fk_deal_fills_fill_id_trade_fills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deal_id', 'fill_id', name=op.f('pk_deal_fills'))
    )
    op.create_table('deal_trade_refs',
    sa.Column('deal_id', sa.String(length=36), nullable=False),
    sa.Column('exchange', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('exchange_trade_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_trade_refs_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deal_id', 'exchange', 'symbol', 'exchange_trade_id', name=op.f('pk_deal_trade_refs'))
    )
    op.create_table('pnl_ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_run_id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('fill_id', sa.String(length=36), nullable=True),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_type', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bot_run_id'], ['bot_runs.id'], name=op.f('fk_pnl_ledger_entries_bot_run_id_bot_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fill_id'], ['trade_fills.id'], name=op.f('fk_pnl_ledger_entries_fill_id_trade_fills'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_pnl_ledger_entries_position_id_positions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pnl_ledger_entries'))
    )
    op.create_index(op.f('ix_pnl_ledger_entries_bot_run_id'), 'pnl_ledger_entries', ['bot_run_id'], unique=False)
    op.create_index(op.f('ix_pnl_ledger_entries_position_id'), 'pnl_ledger_entries', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pnl_ledger_entries_position_id'), table_name='pnl_ledger_entries')
    op.drop_index(op.f('ix_pnl_ledger_entries_bot_run_id'), table_name='pnl_ledger_entries')
    op.drop_table('pnl_ledger_entries')
    op.drop_table('deal_trade_refs')
    op.drop_table('deal_fills')
    op.drop_index(op.f('ix_trade_fills_bot_run_id'), table_name='trade_fills')
    op.drop_table('trade_fills')
    op.drop_index(op.f('ix_position_snapshots_position_id'), table_name='position_snapshots')
    op.drop_table('position_snapshots')
    op.drop_index(op.f('ix_deals_position_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_closed_at'), table_name='deals')
    op.drop_index(op.f('ix_deals_bot_run_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_positions_bot_run_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_bot_run_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_bot_capital_allocation_bot_run_id'), table_name='bot_capital_allocation')
    op.drop_table('bot_capital_allocation')
    op.drop_index(op.f('ix_bot_runs_bot_id'), table_name='bot_runs')
    op.drop_table('bot_runs')
    op.drop_index(op.f('ix_bot_configs_bot_id'), table_name='bot_configs')
    op.drop_table('bot_configs')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_bots_user_id'), table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
