LANGUAGES = {
    "ru": {
        "button_save": "Сохранить",
        "trial_ended": "Время использования пробной версии истекло",
        "button_test": "Тест",
        "button_run": "Старт",
        "button_back_to_settings": "К настройкам",
        "button_back_to_log": "К логу",
        "button_take_profit": "Фикс и остановка бота",
        "button_manual_avg": "Усреднить вручную",
        "button_clear": "Стереть базу данных",
        "button_stop": "Стоп",
        "menu_file": "Файл",
        "menu_exit": "Выход",
        "menu_options": "Опции",
        "menu_lang": "Язык",
        "menu_settings": "Настройки",
        "menu_current_sett": "Текущие настройки",
        "menu_trade_stat": "Статистика торгов",
        "menu_show_stat": "Показать статистику",
        "menu_help": "Помощь",
        "menu_help_help": "Помощь",
        "menu_about": "О боте",
        "exchange_label": "Биржа",
        "bottype_label": "Режим бота",
        "base_coin_label": "Базовые монеты*",
        "quote_coin_label": "Квотируемая валюта*",
        "market_label": "Пара*",
        "algorithm_label": "Алгоритм*",
        "margin_mode_label": "Режим маржи",
        "grow_first_label": "Какую валюту накапливать*",
        "first_step_label": "Отступ первого шага, %",
        "lift_step_label": "Отступ подтяжки ордеров, %",
        "range_cover_label": "Перекрытие хода цены, %",
        "free_dynamic_so_label": "Использовать динамические СО",
        "free_dynamic_so_yes_definition": "включена стратегия размещения страховочных ордеров (СО) по динамической сетке (требуется использование индикаторов)",
        "free_dynamic_so_no_definition": "стратегия выставления страховочных ордеров (СО) по динамической сетке не будет использована",
        "dynamic_so_label": "Расстояние между СО, %",
        "log_distribution_label": "Логарифм. распределение",
        "log_distribution_definition": "Если log_coeff = 1.0, то логарифмическое распределение ордеров отключено.\nПри log_coeff < 1, то логарифмическое распределение позволяет первым ордерам исполняться быстрее, чем последующим если или наоборот, первым ордерам исполняться медленнее, чем последующим при log_coeff > 1.\nРекомендуемые параметры 0.75 - 1.25",
        "trailing_label_long": "Лонг-сквиз и трейлинг продажи*",
        "trailing_label_short": "Шорт-сквиз и трейлинг покупки*",
        "take_profit_options_label": "Способы тейк-профита*",
        "squeeze_profit_label": "Профит сквиз-ордера, %",
        "trailing_stop_label": "Трейлинг-стоп отступ, %",
        "limit_stop_label": "Трейлинг-лимит отступ, %",
        "squeeze_profit_definition": "профит для ловли сквиза (задается более высокое значение по сравнению с запланированным профитом)",
        "trailing_stop_definition": "уровень триггер-цены стоп-ордера, задается в % отступа от текущей цены (Активируется если сквиз цена не была достигнута)",
        "limit_stop_definition": "уровень цены исполнения стоп-ордера, задается в % отступа от триггер-цены",
        "use_rsi_label": "Использовать RSI индикатор",
        "use_dynamic_so_label": "Динамическое усреднение*",
        "use_dynamic_so_yes_definition": "Используется DSO функционал с динамическим усреднением (выставление страховочных ордеров в зависимости от движения цены на рынке)",
        "use_dynamic_so_no_definition": "Используется стандартный DCA функционал с выставлением статической сетки ордеров",
        "bottype_label_single_definition": "Используется режим работы с одной торговой парой",
        "bottype_label_multi_definition": "Используется мультивалютный режим работы. Монеты, подлежащие торговле, должны быть отделены друг от друга запятой",
        "preset_definition": "Переключение пресетов для настройки различных сочетаний индикаторов, обеспечивающих точки входа, усреднения или выхода из рынка",
        "use_price_definition": "При использовании цены пресет активируется при одновременном развороте как CCI, так и цены монеты. При отключении цены пресет работает при пересечении уровня CCI",
        "timeframe_label": "Таймфреймы",
        "use_global_timeframe_label": "Использовать глобальный ТФ",
        "global_timeframe_label": "Глобальный тайфрейм",
        "use_global_stoch_label": "Использовать G/STOCH",
        "global_stoch_long_label": "G/STOCH long (upper/lower)",
        "global_stoch_short_label": "G/STOCH short (upper/lower)",
        "first_so_coeff_label": "1СО coeff",
        "first_so_coeff_definition": "коэффициент для первого усредняющего ордера, позволяет двигать вверх и вниз цену первого СО",
        "dynamic_so_coeff_label": "2СО coeff",
        "dynamic_so_coeff_definition": "увеличивает отступ усредняющего ордера для каждого последующего усреднения (применяется со второго СО)",
        "cci_length_label": "CCI length",
        "ema200_and_delta_label": "EMA200 length / delta, %",
        "macd_label": "MACD S, F, Signal",
        "rsi_atr_efi_length_label": "RSI, ATR, EFI length",
        "bb_label": "BB period / deviation",
        "supertrend_label": "Supertrend period/multiplier",
        "martingale_label": "DCA, coeff",
        "general_settings_label": "БАЗОВЫЕ НАСТРОЙКИ",
        "entry_conditions_label": "УСЛОВИЯ ВХОДА",
        "averaging_conditions_label": "УСЛОВИЯ УСРЕДНЕНИЯ",
        "exit_conditions_label": "УСЛОВИЯ ВЫХОДА",
        "profit_label": "Профит, %",
        "market_definition": "торговая пара в формате XXX/USDT. Вы можете выбрать любую пару, доступную на фьючерсных торгах: BTC/USDT, ETH/USDT, и т.д.",
        "algorithm_long_definition": "для работы в алгоритме \"long\" ваш депозит должен состоять из второй валюты торговой пары.",
        "algorithm_short_definition": "для работы в алгоритме \"short\" ваш депозит должен состоять из первой валюты торговой пары.",
        "grow_first_1_definition": "выбрана первая валюта, накапливаем",
        "grow_first_2_definition": "выбрана вторая валюта, накапливаем",
        "dont_forget_to_save": "Если сделаны изменения, сохраните настройки, нажав на кнопку \"Save settings\"",
        "timeframe_definition": "таймфреймы для работы стратегии динамического усреднения. Рекомендуемые значения \"5m-2h\"",
        "global_timeframe_definition": "глобальный таймфрейм для использования при анализе иникаторов. Рекомендуемые значения \"1h-8h\"",
        "ema200_delta_definition": "Длина EMA200 и отступ от значения кривой EMA200 для определения FLAT тренда",
        "martingale_definition": "DCA/мартингейл. Коэффициент увеличения объема страховочных ордеров",
        "profit_definition": "профит одного цикла закупки-продажи. Рекомендуемое значение: 0.4 - 2%",
        "buy_total_label": "Общее количество ордеров",
        "buy_active_label": "Количество активных СО",
        "sell_total_label": "Количество sell-ордеров",
        "time_sleep_label": "Пауза, сек. / коэфф.",
        "time_sleep_definition": "пауза между циклами проверки состояния ордеров (устанавливается в секундах), а также коэффициент умножения паузы (для случаев поиска входа в рынок и иных случаев, где короткая пауза не важна)",
        "can_spend_first_currency_percent_definition": "депо второй валюты (в процентах)",
        "can_spend_second_currency_percent_definition": "депо первой валюты (в процентах)",
        "can_spend_first_currency_coin_definition": "депо второй валюты (в монетах)",
        "can_spend_second_currency_coin_definition": "депо первой валюты (в монетах)",
        "buy_total_definition": "общее количество ордеров, которые будут размещены на бирже",
        "first_step_definition": "первый ордер будет размещен с указанным отступом от текущей цены первой валюты торговой пары",
        "lift_step_definition": "если текущая цена рынка пойдет ниже значения отступа, ордеры будут выставлены заново",
        "range_cover_definition": "разбег цены, в пределах которого будут размещены усредняющие (страховочные) ордеры",
        "co_range_cover_definition": "отступ цены следующего страховочного (усредняющего) ордера",
        "use_tf_switching_definition": "Использовать функцию переключения таймфреймов (при сильном падении рынка для более эффективного усреднения рабочий таймфрейм будет переключен на повышенный: с 5m на 15m и т.д.)",
        "can_spend_label": "Рабочий депозит",
        "bo_amount_label": "Объем БО",
        "so_amount_label": "Объем всех СО",
        "leverage_label": "Кредитное плечо",
        "fix_manually": "Фикс вручную",
        "one_or_more_label": " Способ размещения ордеров*",
        "one_or_more_one_long_definition": "выбрано \"one\": усредняющие buy-ордеры будут размещены по очереди, каждый - по достижению своей цены покупки",
        "one_or_more_more_long_definition": "выбрана опция \"grid\": усредняющие buy-ордеры будут размещены при старте и будут ожидать исполнения",
        "one_or_more_one_short_definition": "выбрано \"one\": усредняющие sell-ордеры будут размещены по очереди, каждый - по достижению своей цены продажи",
        "one_or_more_more_short_definition": "выбрана опция \"grid\": усредняющие sell-ордеры будут размещены при старте и будут ожидать исполнения",
        "one_order_label": "поочерёдно",
        "more_order_label": "все_сразу",
        "api_key_secret_not_defined": "API KEY и API SECRET не определены.\nВведите их в файле config.toml",
        "invalid_number_format": "Недопустимый формат числа. Проверьте все значения.\nДробные числа должны содержать знак точки, а не запятой",
        "market_format_incorrect": "Торговая пара задана неверно.\nИспользуйте следующий формат торговых пар:\nBTC/USDT, XVG/USDT..., и т.д.\nETH/BTC, DASH/BTC..., и т.д.\nETC/ETH, NEO/ETH..., и т.д.",
        "orders_total_incorrect": "Количество buy/sell ордеров задано не верно.\nМинимальное количество - 2 ордера, максимальное - 50.\nЕсли вы хотите работать без усреднений, установите 2 ордера, отступ динамического СО = 100%, DCA = 0, депозит в 2 раза больше желаемого",
        "time_sleep_incorrect": "Пауза между циклами проверки задана не верно.\nМинимальное значение - 0.5 сек., максимальное - 21600 сек.",
        "stoch_cci_incorrect": "Конфигурация настроек задана не верно",
        "the_bot_stopped": "Фикс-ордер исполнен. Бот остановлен",
        "sell_not_placed": "Sell-ордер не выставлен. Бот остановлен. Ошибка:",
        "buy_not_placed": "Buy-ордер не выставлен. Бот остановлен. Ошибка:",
        "log_stopped": " Бот остановлен.",
        "log_error": "Ошибка:",
        "waiting_for_balance": "Не хватает баланса. Ждем продаж от других ботов или пополнения депозита вручную",
        "no_balance": "На балансе нет средств для усреднения",
        "log_manual_averaging_ok": "ВНИМАНИЕ! ЗАПУЩЕНО РУЧНОЕ УСРЕДНЕНИЕ!",
        "log_manual_sell_ok": "ВНИМАНИЕ! ЗАПУЩЕНА РУЧНАЯ ПРОДАЖА РАНЕЕ ЗАКУПЛЕННЫХ БОТОМ МОНЕТ!",
        "log_manual_buy_ok": "ВНИМАНИЕ! ЗАПУЩЕНА РУЧНАЯ ПОКУПКА РАНЕЕ ПРОДАННЫХ БОТОМ МОНЕТ!",
        "log_check_whitelist": "Проверяем белый список монет для добавления в торги",
        "log_check_whitelist_ok": "Найдены условия для начала торгов по торговой паре",
        "log_check_whitelist_add": "Добавляем в перечень базовых монет",
        "log_trend": "тренда",
        "log_create_buy_macd_long": "Создаем ордер на покупку с учетом глобального тренда",
        "log_create_buy_long": "Создаем ордер на покупку",
        "log_current_price": "Текущая цена",
        "log_liquidation_price": "Цена ликвидации",
        "log_close_price": "Цена закрытия позиции",
        "log_previous_price": "Предыдущая цена",
        "log_current_cci": "Текущее значение cci",
        "log_previous_cci": "Предыдущее значение cci",
        "log_current_ma": "Текущее значение ma_1 и ma_2",
        "log_previous_ma": "Предыдущее значение ma_1 и ma_2",
        "log_current_rsi": "Текущее значение rsi и smarsi",
        "log_previous_rsi": "Предыдущее значение rsi и smarsi",
        "log_current_xxx": "Текущие",
        "log_previous_xxx": "Предыдущие",
        "log_free_balance": "Баланс составляет",
        "log_free": "Свободно",
        "log_signal_found": "ОБНАРУЖЕН СИГНАЛ",
        "log_no_signal_yet": "Пока нет сигнала",
        "log_for_closing": "на закрытие позиции",
        "log_closing_position": "ЗАКРЫВАЕМ ПОЗИЦИЮ",
        "log_remaining_fix_value": "Объем фикс-ордера:",
        "log_remaining_remain": "Проверка частичного исполнения. Остаток:",
        "log_remaining_market_long": "Запускаем маркет-ордер на продажу остатка",
        "log_remaining_market_short": "Запускаем маркет-ордер на покупку остатка",
        "log_try_to_sell_remaining": "Пытаемся продать остаток",
        "log_try_to_buy_remaining": "Пытаемся откупить остаток",
        "log_timeframe_switched": "ТАЙМФРЕЙМ УСРЕДНЕНИЯ ПЕРЕКЛЮЧЕН НА",
        "log_tf_switch_reason_ema_long": "Текущая цена ниже глобальной EMA",
        "log_tf_switch_reason_ema_short": "Текущая цена выше глобальной EMA",
        "log_tf_switch_reason_order": "Выставлен триггер-ордер",
        "log_tf_switch_reason_candle_long": "Рынок падает слишком быстро",
        "log_tf_switch_reason_candle_short": "Рынок растет слишком быстро",
        "log_tf_switch_reason_stoch": "старшего таймфрейма в канале усреднения",
        "log_buy_price": "Пробуем купить по цене",
        "log_sell_price": "Пробуем продать по цене",
        "log_order_amount": "Сумма",
        "log_create_order": "создаю ордер",
        "log_buy_order_created_long": "Создан ордер на покупку",
        "log_failed_to_create": "Не удалось создать ордер",
        "log_failed_to_create_no_money": "Не достаточно средств для размещения ордера",
        "log_try_to_average_remaining_dep": "Депозита не хватает. Пробуем усредниться на оставшийся депозит",
        "log_total_spent_long": "Итого на сделку было потрачено",
        "log_obtained": "получено",
        "log_to_get_a_profit_long": "Чтобы выйти в плюс, необходимо продать купленную валюту по курсу",
        "log_after_fee": "Тогда после вычета комиссии",
        "log_will_remain": "останется сумма",
        "log_total_profit": "Итоговая прибыль составит",
        "log_rate_for_sell_long": "Текущий курс продажи",
        "log_create_sell_rate_long": "Создаю ордер на продажу по курсу",
        "log_create_sell_squeeze_rate_long": "Создаю сквиз-ордер на продажу по курсу",
        "log_create_stop_limit_long": "Фиксируем цену исполнения стопа",
        "log_profit": "профит",
        "log_more_sell_created_long": "будет создано несколько sell-ордеров, каждый со своим профитом",
        "log_one_sell_created_long": "создается один sell-ордер по средней цене закупки buy-ордеров",
        "log_check_trend": "Текущие тренды:",
        "log_current_trend": "ТРЕНД",
        "log_check_orders": "Выполняем проверку состояния ордеров",
        "log_check_total": "Всего запланировано ордеров",
        "log_check_CO": "выставлено",
        "log_no_more_co": "К сожалению, все усредняющие ордеры уже выставлены :(",
        "log_avr_buy_price_is": "Средняя цена входа (long)",
        "log_avr_sell_price_is": "Средняя цена входа (short)",
        "log_no_more_co_telegram": "Караул! По этой паре больше нечем усредняться",
        "log_order": "Ордер",
        "log_order_filled": "уже выполнен!",
        "log_order_canceled": "отменён!",
        "log_order_market_canceled_DB": "помечен как отменённый в БД",
        "log_order_with_amount": "oрдер объемом",
        "log_unknown_pos_det": "Обнаружена размещенная пользователем поза",
        "log_record_pos": "Записываем данные позы в БД",
        "log_we_have_pos": "Имеется поза",
        "log_with_amount": "объемом",
        "log_order_with_price": "и ценой",
        "log_order_not_filled_yet": "еще не выполнен",
        "log_order_remains": "Остаток",
        "log_order_SELL_filled_long": "Исполнен SELL объемом",
        "log_order_filled_long": "Закрыта LONG позиция объемом",
        "log_order_STOP_filled_long": "Сработал STOP-loss. Закрыта LONG позиция объемом",
        "log_order_SQUEEZE_filled_long": "Исполнен LONG-сквиз объемом",
        "log_order_SQUEEZE_canceled_long": "Отменен LONG-сквиз объемом",
        "log_order_STOP_canceled_long": "Отменен STOP-sell",
        "log_telegram": "Сообщаем в Telegram",
        "log_filled_buy_sell_long": "Для выполненного ордера на покупку выставляем ордер на продажу",
        "log_max_buy_long": "Максимальная цена buy-ордера",
        "log_bid_price_long": "Цена Bid при закупке",
        "log_time_remained": "До отмены ордеров осталось: ",
        "log_time_min": "мин.",
        "log_time_sec": "сек.",
        "log_current_trend_BULL": "Локальный тренд по EMA200 БЫЧИЙ. Проверяем не сменился ли тренд",
        "log_current_trend_changed_long": "Тренд сменился, отменяем buy-ордеры",
        "log_current_trend_the_same": "Тренд прежний, отменять ордеры не требуется",
        "log_current_trend_FLAT": "Локальный тренд по EMA200 \"ФЛЕТ\". Проверяем не сменился ли тренд",
        "log_current_trend_BEAR": "Локальный тренд по EMA200 МЕДВЕЖИЙ. Проверяем не сменился ли тренд",
        "log_check_up_long": "Проверяем нужно ли подтягивать ордеры",
        "log_orders_up_long": "Цена поднялась, перевыставляем ордера. ОТМЕНЯЕМ ордер объемом",
        "log_check_up_short": "Проверяем нужно ли двигать ордеры ниже",
        "log_orders_up_short": "Цена опустилась, перевыставляем ордера. ОТМЕНЯЕМ ордер объемом",
        "log_orders_new_qfl": "Найдена новая QFL база. ОТМЕНЯЕМ ордер объемом",
        "log_reversal_pattern_found": "НАЙДЕН РАЗВОРОТНЫЙ ПАТТЕРН. НАЧИНАЕМ МОНИТОРИТЬ",
        "log_with_qfl_base": "С БАЗОЙ",
        "log_price_out_of_base": "ЦЕНА УШЛА ЗА РАМКИ НАЙДЕННОЙ БАЗЫ",
        "log_entry_with_algo": "ВХОДИМ В",
        "log_time_expired": "Время жизни ордеров истекло. Пора перевыствить ордеры",
        "log_filled_partially": "выполнен частично. Ждем исполнения",
        "log_no_orders": "Неисполненных ордеров в БД нет, не пора ли создать новые?",
        "log_create_buys_long": "Создаем ордеры на покупку",
        "log_new_sell_created_long": "Выставлен новый ордер на продажу",
        "log_create_buy_macd_short": "Создаем ордер на продажу с учетом глобального тренда",
        "log_create_buy_short": "Создаем ордер на продажу",
        "log_buy_order_created_short": "Создан ордер на продажу",
        "log_total_spent_short": "Итого по сделке было продано",
        "log_to_get_a_profit_short": "Что бы выйти в плюс, необходимо откупить проданную валюту по курсу",
        "log_rate_for_sell_short": "Текущий курс покупки",
        "log_create_sell_rate_short": "Ордер на покупку будет исполнен по курсу",# изменено
        "log_create_sell_squeeze_rate_short": "Создаю сквиз-ордер на покупку по курсу",
        "log_create_stop_limit_short": "Фиксируем цену исполнения стопа",# изменено
        "log_more_sell_created_short": "будет создано несколько buy-ордеров, каждый со своим профитом",
        "log_one_sell_created_short": "создается один buy-ордер по средней цене продажи sell-ордеров",
        "log_order_SELL_filled_short": "Исполнен BUY объемом",
        "log_order_filled_short": "Закрыта SHORT позиция объемом",
        "log_order_STOP_filled_short": "Сработал STOP-loss. Закрыта SHORT позиция объемом",
        "log_order_SQUEEZE_filled_short": "Исполнен SHORT-сквиз объемом",
        "log_order_SQUEEZE_canceled_short": "Отменен SHORT-сквиз объемом",
        "log_order_STOP_canceled_short": "Отменен STOP-buy",# изменено
        "log_order_STOP_not_filled": "Стоп еще не исполнен. Ждём изменения цены",# изменено
        "log_filled_buy_sell_short": "Для выполненного ордера на продажу выставляем ордер на покупку",
        "log_min_buy_short": "Минимальная цена sell-ордера",
        "log_bid_price_short": "Цена Ask при продаже",
        "log_current_trend_changed_short": "Тренд сменился, отменяем sell-ордеры",
        "log_create_buys_short": "Создаем ордеры на продажу",
        "log_new_sell_created_short": "Выставлен новый ордер на покупку",
        "log_initial_sell_price": "Цена продажи базового ордера",
        "log_initial_buy_price": "Цена покупки базового ордера",
        "log_5_days_from_BO": "Базовый ордер был исполнен более 5 дней назад. Проверьте бот",
        "log_order_squeeze_canceled_DB_long": "Сквиз-ордер отменен, начинаем трейлинг sell-ордера",
        "log_order_squeeze_canceled_DB_short": "Сквиз-ордер отменен, начинаем трейлинг buy-ордера",
        "log_order_stop_canceled_DB_long": "Цена поднялась, отменяем существующий трейлинг стоп-ордер",
        "log_order_stop_canceled_DB_short": "Цена опустилась, отменяем существующий трейлинг стоп-ордер",
        "log_create_stop": "Инициируем трейлинг стоп-ордер",# изменено
        "log_create_new_stop_long": "Цена поднялась. Инициируем новый стоп-ордер",# изменено
        "log_create_new_stop_short": "Цена опустилась. Инициируем новый стоп-ордер",# изменено
        "log_create_limit_stop_long": "Цена опустилась. Реализуем стоп-ордер по лимитной цене",
        "log_create_limit_stop_short": "Цена поднялась. Реализуем стоп-ордер по лимитной цене",
        "log_create_market_stop_long": "Цена опустилась. Выставляем стоп-ордер по текущей цене покупки",
        "log_create_market_stop_short": "Цена поднялась. Выставляем стоп-ордер по текущей цене продажи",
        "log_profit_price_long_is": "Цена безубыточной продажи",
        "log_profit_price_short_is": "Цена безубыточной покупки",
        "log_stop_will_be_filled_at": "Стоп-ордер будет исполнен по цене",# to be delited
        "log_if_price_went_down": "если она опустится ниже",# to be delited
        "log_if_price_went_up": "если она поднимется выше",# to be delited
        "log_next_stop_price": "Трейлинг фикс-ордера будет начат при достижении цены",# изменено
        "log_next_avarage_sell_price": "Цена следующего усредняющего sell-ордера будет не менее",
        "log_next_avarage_buy_price": "Цена следующего усредняющего buy-ордера будет не более",
        "log_dynamic_on": "Подключено динамическое усреднение",
        "log_check_avarage_buy": "Проверяем, не пора ли выставлять усредняющий buy-ордер?",
        "log_check_avarage_sell": "Проверяем, не пора ли выставлять усредняющий sell-ордер?",
        "log_no_avarage": "Пока рано усредняться, ждем изменения цены и сигнала индикаторов",
        "log_start_avarage_long": "Цена понизилась. Проверяем можно ли делать усреднение",
        "log_start_avarage_short": "Цена повысилась. Проверяем можно ли делать усреднение",
        "log_ema_global_allows_buy": "Индикатор EMA_GLOBAL позволяет выставить buy-ордеры",
        "log_ema_global_allows_sell": "Индикатор EMA_GLOBAL позволяет выставить sell-ордеры",
        "log_ema_global_not_allows": "EMA_GLOBAL не рекомендует входить в рынок",
        "log_ema_entry_allows_buy": "Индикатор EMA_ENTRY позволяет выставить buy-ордеры",
        "log_ema_entry_allows_sell": "Индикатор EMA_ENTRY позволяет выставить sell-ордеры",
        "log_ema_entry_not_allows": "EMA_ENTRY не рекомендует входить в рынок",
        "log_stoch_allows": "Параметры",
        "log_tv_allows_entry": "Cигнал TradingView позволяет войти в рынок",
        "log_tv_allows_sell": "Получен сигнал TradingView на выход из рынка. Продаем по рыночной цене",
        "log_tv_allows_buy": "Получен сигнал TradingView на выход из рынка. Покупаем по рыночной цене",
        "log_cross_sell": "сигнализирует на выход из рынка. Продаем по рыночной цене",
        "log_cross_buy": "сигнализирует на выход из рынка. Покупаем по рыночной цене",
        "log_cci_cross_not_allows_entry": "ССI не позволяет войти в рынок",
        "log_cci_cross_allows_entry": "ССI позволяет войти в рынок",
        "log_cci_cross_not_allows_avg": "ССI не позволяет усредняться",
        "log_cci_cross_allows_avg": "ССI позволяет усредняться",
        "log_xxx_not_allows_avg": "не позволяет усредняться",
        "log_xxx_allows_avg": "позволяет усредняться",
        "log_cci_cross_not_allows_exit": "ССI не позволяет выйти из рынка",
        "log_cci_cross_allows_exit": "ССI позволяет выйти из рынка",
        "log_stoch_not_allows": "не рекомендует торговлю",
        "log_stoch_allows_exit": "позволяет выйти из рынка",
        "log_price_not_allows_exit": "не позволяет выйти из рынка",
        "log_stoch_not_allows_exit": "или индикаторы не позволяют выйти из рынка",
        "log_waiting_for_price_long": "Ждем цены bid более",
        "log_waiting_for_price_short": "Ждем цены ask менее",
        "log_cci_allows": "CCI позволяет войти в",
        "log_cci_not_allows": "CCI не рекомендует торговлю",
        "log_rsi_allows": "RSI позволяет войти в",
        "log_rsi_not_allows": "RSI не рекомендует торговлю",
        "log_stoch_not_in_channel_long": "еще не в канале. Ждем понижения цены.",
        "log_stoch_not_in_channel_short": "еще не в канале. Ждем повышения цены.",
        "log_good_margin_BO": "Цена соответствует торговому каналу. Выставляем базовый ордер",
        "log_margin": "Ценовой канал:",
        "log_margin_top": "верхняя граница =",
        "log_margin_bottom": "нижняя граница =",
        "log_good_margin": "Цена соответствует торговому каналу. Пробуем усредняться",
        "log_bad_margin": "Цена ушла за границу торгового канала. Ждем изменения цены",
        "log_exit_price_long": "Продажа запустится при цене не менее",
        "log_exit_price_short": "Покупка запустится при цене не более",
        "telegram_filled": "ИСПОЛНЕН",
        "telegram_from": "из",
        "telegram_bought": "BUY объемом ",
        "telegram_stop_bought": "STOP-buy объемом ",
        "telegram_squeeze_bought": "BUY-сквиз объемом ",
        "telegram_stop_loss": "STOP-LOSS объемом ",
        "telegram_stop_loss_filled": "Сработал STOP-loss",
        "telegram_sold": "SELL объемом ",
        "telegram_stop_sold": "STOP-sell объемом ",
        "telegram_squeeze_sold": "SELL-сквиз объемом ",
        "telegram_for": "по цене",
        "telegram_placed": "РАЗМЕЩЁН",
        "telegram_placed_buy": "BUY объемом ",
        "telegram_placed_stop_buy": "STOP-buy объемом ",
        "telegram_placed_squeeze_buy": "BUY-сквиз объемом ",
        "telegram_placed_sell": "SELL объемом ",
        "telegram_placed_stop_sell": "STOP-sell объемом ",
        "telegram_placed_squeeze_sell": "SELL-сквиз объемом ",
        "log_no_position": "Позы нет. Проверяем нет ли условий для входа в рынок",
        "log_no_conditions": "Пока нет условий для входа. Ожидайте или скорректируйте настройки",
        "telegram_close_position": "Позиция закрыта",
        "telegram_deal_profit": "Доход сделки",
        "trade_statistics": "Статистика торговли",
        "statistics_long": "алгоритм \"LONG\"",
        "statistics_bought_long": "Закуплено монет на сумму",
        "statistics_sold_long": "Продано монет на сумму",
        "statistics_if_will_sell_long": "Если закупленные монеты будут проданы, то доход составит",
        "statistics_or": "что составляет",
        "statistics_short": "алгоритм \"SHORT\"",
        "statistics_sold_short": "Продано монет на сумму",
        "statistics_bought_short": "Откуплено монет на сумму",
        "statistics_if_will_buy_short": "Если проданные монеты будут откуплены, то доход составит",
        "statistics_are_not_available": "Статистика пока недоступна",
        "test_buy_price": "цена",
        "test_spent": "Потрачено",
        "orders_spent": "орд.",
        "test_sell_price": "цена продажи",
        "test_fix_price": "цена фикса",
        "test_sold": "продано",
        "test_received": "размер позы",
        "test_liquidation": "цена ликвидации",
        "test_price_increase": "прирост цены",
        "test_profit": "общий доход",
        "test_delta": "разница",
        "test_profit_B": "Доход",
        "test_if_all_orders_filled": "Если все ордеры исполнятся, общий доход составит",
        "test_if_first_orders_filled": "Если исполнятся только первые",
        "test_orders_prifit_will_be": "ордеров, доход составит",
        "test_or": "или",
        "test_of_depo": "% от депо",
        "test_var_1": "Если все ордеры исполнятся:",
        "test_var_average_long": "Средняя цена входа составит",
        "test_var_average_short": "Средняя цена входа составит",
        "test_var_pnl": "Просадка при реализации последнего СО составит",
        "test_var_liquidation": "До реализации последнего СО наступит ликвидация. Пересмотрите настройки и риски",
        "test_var_sell_price_long": "Sell-ордер будет выставлен по цене",
        "test_var_sell_price_short": "Buy-ордер будет выставлен по цене",
        "test_var_profit": "Общий доход составит",
        "test_var_2": "Вариант 2 (Если исполнятся только первые",
        "test_var_orders": "орд.)",
        "no_trend_change": "Ищем точку разворота для усреднения позиции",
        "avr_order_level_was": "Цена усреднения по сетке",
        "price_delta": "Разница",
        "bo_price_delta": "Разница с базовым ордером",
        "average_price_delta": "ROE",
        "average_position_price_delta": "Разница со средней ценой позиции",
        "bid_price": "Цена bid",
        "fast_STOCH": "fast",
        "slow_STOCH": "slow",
        "log_exit_stop_loss_allows": "СРАБОТАЛ СТОП ЛОСС. БОТ ВЫНУЖДЕН ЗАФИКСИРОВАТЬ УБЫТОК",
        "log_emergency_averaging": "ЗАПУЩЕНО ЭКСТРЕННОЕ УСРЕДНЕНИЕ!",
        "log_next_avr_for_manual": "Для ручного усреднения потребуется",
        "trend_changes_avr_found": "Точка разворота найдена",
        "trend_changes_avr_price_is": "Пробуем усредниться по текущей цене",
        "price_check": "Ждем изменения цены или показания индикаторов",
        "price_go_up_long": "Цена выше допустимой, усреднение не требуется",
        "price_go_down_short": "Цена ниже допустимой, усреднение не требуется",
        "stoch_fastk_period_label": "STOCH: %K, %D, замедление",
        "stoch_fastk_period_definition": "значения быстрой, медленной кривой и замедления для усреднения по сигналу от стохастического осциллятора",
        "stoch_level_definition": "уровни показаний стохастического осциллятора, используемые для усреднения в алгоритмах SHORT/LONG",
        "log_buy_string_found": "Найдена MAIL запись buy",
        "log_sell_string_found": "Найдена MAIL запись sell",
        "exit_timeframe_label": "Таймфрейм выхода",
        "exit_use_tv_signals_label": "Использовать сигнал TradingView",
        "entry_use_stoch_or_cci_label": "Использовать STOCH / CCI",
        "avg_use_stoch_or_cci_label": "Использовать STOCH / CCI",
        "exit_use_stoch_or_cci_label": "Использовать STOCH / CCI",
        "entry_use_stoch_or_rsi_label": "Использовать STOCH / RSI",
        "avg_use_stoch_or_rsi_label": "Использовать STOCH / RSI",
        "exit_use_stoch_or_rsi_label": "Использовать STOCH / RSI",
        "exit_use_stoch_label": "Использовать STOCH",
        "exit_use_cci_label": "Использовать CCI",
        "use_price_label": "Использовать цену",
        "exit_stoch_up_long_label": "Long STOCH (upper/lower)",
        "exit_stoch_up_short_label": "Short STOCH (upper/lower)",
        "exit_cci_level_label": "Выход по CCI (short/long)",
        "exit_rsi_level_label": "Выход по RSI (short/long)",
        "price_delta_label": "Разница от close (short/long)",
        "avg_price_delta_label": "Разница цены (short/long)",
        "exit_timeframe_definition": "таймфрейм для определения показаний индикаторов при реализации тейк-профита",
        "exit_use_tv_signals_definition": "функция использования сигналов индикаторов или стратегий ТрейдингВью для тейк-профита",
        "exit_use_stoch_definition": "функция использования STOCH для тейк-профита",
        "exit_use_cci_definition": "функция использования CCI для тейк-профита",
        "exit_use_rsi_definition": "функция использования RSI для тейк-профита",
        "exit_stoch_level_definition": "уровни показаний стохастического осциллятора, используемые для тейк-профита в алгоритмах SHORT/LONG",
        "exit_cci_level_definition": "уровни показаний CCI, используемые для тейк-профита в алгоритмах SHORT/LONG",
        "exit_rsi_level_definition": "уровни показаний RSI, используемые для тейк-профита в алгоритмах SHORT/LONG",
        "entry_by_indicators_label": "Вход по индикаторам",
        "entry_timeframe_label": "Таймфрейм входа",
        "entry_preset_label": "Пресет входа",
        "exit_preset_label": "Пресет выхода",
        "entry_basic_indicator_label": "Приоритетный индикатор",
        "avg_basic_indicator_label": "Приоритетный индикатор",
        "exit_basic_indicator_label": "Приоритетный индикатор",
        "exit_profit_level_label": "Профит / стоп-лосс, %",
        "entry_stoch_up_long_label": "Long STOCH (upper/lower)",
        "entry_stoch_up_short_label": "Short STOCH (upper/lower)",
        "entry_cci_level_label": "Вход по CCI (short/long)",
        "entry_rsi_level_label": "Вход по RSI (short/long)",
        "cci_cross_crossover": "Кросс: снизу вверх",
        "cci_cross_crossunder": "Кросс: сверху вниз",
        "qfl_N_label": "Свечей до high/low",
        "qfl_M_label": "Свечей после high/low",
        "1_qfl_h_l_percent_label": "Отступ цены открытия, %",
        "2_qfl_h_l_percent_label": "Отступ цены закрытия, %",
        "ma1_cross_length_label": "Длина MA_1",
        "ma2_cross_length_label": "Длина MA_2",
        "rsi_level_long": "Long RSI (upper/lower)",
        "rsi_level_short": "Short RSI (upper/lower)",
        "smarsi_length_label": "SMA сглаживание",
        "stop_activated": "Подключен простой стоп-лосс. Мониторим цену",
        "bo_global_stop_activated": "Подключен стоп-лосс для базового ордера. Мониторим GLOBAL STOCH",
        "avg_use_tf_switching_label": "Переключать таймфреймы",
        "avg_timeframes_label": "Таймфреймы усреднения",
        "avg_preset_label": "Пресет усреднения",
        "avg_stoch_up_long_label": "Long STOCH (upper/lower)",
        "avg_stoch_up_short_label": "Short STOCH (upper/lower)",
        "avg_cci_level_label": "CCI level (short/long)",
        "avg_rsi_level_label": "RSI level (short/long)",
        "indicators_fine_tuning_label": "НАСТРОЙКИ ИНДИКАТОРОВ",
        "timeframe_switching_label": "ПЕРЕКЛЮЧЕНИЕ ТАЙМФРЕЙМОВ",
        "ema_global_switch_label": "EMA Global триггер",
        "orders_switch_label": "Ордер-триггер",
        "orders_count_label": "Номер ордер-триггера",
        "last_candle_switch_label": "Триггер по счёту свечей",
        "last_candle_count_label": "Счёт свечей / номер ордера",
        "stoch_adjustment_label": "STOCH поправка канала, %",
        "miscellaneous_label": "ПРОЧЕЕ",
        "immediate_so_label": "Выставлять СО по рынку",
        "back_profit_label": "Снижение уровня ТП, %",
        "so_safety_price_label": "Страховочный отступ СО, %",
        "emergency_averaging_label": "Экстренное усреднение, %",
        "use_margin_label": "Использовать ценовой коридор",
        "margin_top_and_bottom_label": "Верхняя/нижняя граница",
        "cancel_on_trend_label": "Отмена БО при смене тренда",
        "use_stoch_rsi": "Использовать STOCH_RSI",
        "log_check_tf": "Проверьте введенный в конфигурационный файл таймфрейм. Похоже, что апи биржи не поддерживает его",
        "log_stop_loss_price": "Цена стоп-лосса:",
        "log_planning_stop_loss_price": "Планируемая цена стоп-лосса:",
        "log_not_enough_bnb": "ВНИМАНИЕ! НА ВАШЕМ БАЛАНСЕ НЕДОСТАТОЧНО BNB ДЛЯ ВЫЧЕТА КОМИССИИ",
        "deal_duration": "Длительность сделки",
        "days": "дн.",
        "hours": "ч.",
        "minutes": "мин.",
        "seconds": "сек.",
        "log_entry_preset_chosen": "Выбран пресет входа",
        "log_avg_preset_chosen": "Выбран пресет усреднения",
        "log_exit_preset_chosen": "Выбран пресет выхода",
        "log_global_stoch_allows_entry": "GLOBAL STOCH позволяет войти в рынок",
        "log_global_stoch_not_allows_entry": "GLOBAL STOCH не позволяет войти в рынок",
        "log_global_stoch_allows_avg": "GLOBAL STOCH позволяет усредниться",
        "log_global_stoch_allows_exit": "GLOBAL STOCH позволяет выйти",
    },
    "en": {
        "button_save": "Save settings",
        "trial_ended": "The trial version has expired",
        "button_test": "Test",
        "button_run": "Run",
        "button_clear": "Clear the DB",
        "button_stop": "Stop",
        "button_back_to_settings": "To settings",
        "button_back_to_log": "To logs",
        "button_take_profit": "Take profit and stop",
        "button_manual_avg": "Manual averaging",
        "menu_file": "File",
        "menu_exit": "Exit",
        "menu_options": "Options",
        "menu_lang": "Language",
        "menu_settings": "Settings",
        "menu_current_sett": "Current settings",
        "menu_trade_stat": "Trade statistics",
        "menu_show_stat": "Show statistics",
        "menu_help": "Help",
        "menu_help_help": "Help",
        "menu_about": "About",
        "exchange_label": "Exchange",
        "bottype_label": "Bot type",
        "base_coin_label": "Base coin*",
        "quote_coin_label": "Quote currency*",
        "market_label": "Pair*",
        "algorithm_label": "Algorithm*",
        "margin_mode_label": "Margin mode",
        "grow_first_label": "Currency to accumulate*",
        "first_step_label": "First step indent, %",
        "lift_step_label": "Indent for orders re-place, %",
        "range_cover_label": "Range cover, %",
        "free_dynamic_so_label": "Use dynamic averaging",
        "free_dynamic_so_yes_definition": "the strategy of placing safety orders (SO) on a dynamic grid is enabled (TA indicators are required)",
        "free_dynamic_so_no_definition": "the strategy of placing safety orders (SO) on a dynamic grid will not be used",
        "dynamic_so_label": "Dynamic SO indent, %",
        "log_distribution_label": "Logarithmic distribution",
        "log_distribution_definition": "If log_coeff = 1.0, the logarithmic distribution of orders is disabled.\nIf log_coeff < 1, the logarithmic distribution allows the first orders to be executed faster than the subsequent ones, or vice versa, the first orders to be executed slower than the subsequent ones with log_coeff > 1.\nRecommended values are 0.75 - 1.25",
        "trailing_label_long": "Long-squeeze and sell-trailing*",
        "trailing_label_short": "Short-squeeze and buy-trailing*",
        "take_profit_options_label": "Take profit method*",
        "squeeze_profit_label": "Squeeze order profit, %",
        "trailing_stop_label": "Trailing stop price indent, %",
        "limit_stop_label": "Trailing limit price indent, %",
        "squeeze_profit_definition": "profit for catching a squeeze (set a higher value than the planned profit)",
        "trailing_stop_definition": "the trigger price of the stop order: an indent from the current price in %. Activated if squeeze price has not been reached",
        "limit_stop_definition": "the limit price of the stop order: an indent from the trigger price in %",
        "use_dynamic_so_label": "Dynamic averaging*",
        "use_dynamic_so_yes_definition": "DSO functionality with dynamic averaging is used (placing safety orders depending on the market price movement)",
        "use_dynamic_so_no_definition": "The standard DCA functionality is used (placing a static grid of orders)",
        "bottype_label_single_definition": "The mode of operation with one trading pair is used",
        "bottype_label_multi_definition": "The multi-currency mode of operation is used. The coins to be traded must be separated from each other by a comma",
        "preset_definition": "Switching presets to configure various combinations of indicators that provide entry, averaging or exit points",
        "use_price_definition": "When using the price, the preset is activated when both CCI and the coin price are reversed at the same time. When the price is disabled, the preset works when the CCI level is crossed",
        "timeframe_label": "Timeframes",
        "use_global_timeframe_label": "Use global timeframe",
        "global_timeframe_label": "Global timeframe",
        "use_global_stoch_label": "Use global STOCH",
        "global_stoch_long_label": "G/STOCH long (upper/lower)",
        "global_stoch_short_label": "G/STOCH short (upper/lower)",
        "first_so_coeff_label": "1SO coeff",
        "first_so_coeff_definition": "averaging coeff for the first SO, allows to move up and down the price of the first SO for different trends",
        "dynamic_so_coeff_label": "2SO coeff",
        "dynamic_so_coeff_definition": "dynamic averagin coeff. Increases the margin of the averaging order (applicable starting from the second SO)",
        "cci_length_label": "CCI length",
        "ema200_and_delta_label": "EMA200 length / delta, %",
        "macd_label": "MACD S, F, Signal",
        "rsi_atr_efi_length_label": "RSI, ATR, EFI length",
        "bb_label": "BB period / deviation",
        "supertrend_label": "Supertrend period/multiplier",
        "entry_conditions_label": "ENTRY CONDITIONS",
        "averaging_conditions_label": "AVERAGING CONDITIONS",
        "general_settings_label": "GENERAL SETTINGS",
        "exit_conditions_label": "EXIT CONDITIONS",
        "martingale_label": "DCA, coeff",
        "profit_label": "Profit, %",
        "market_definition": "the pair on which the bot will trade in XXX/USDT format. You can choose any pair traded on the futures: BTC/USDT, ETH/USDT, etc.",
        "algorithm_long_definition": "to work in \"long\" your deposit on the exchange must consist of the second currency in the trading pair.",
        "algorithm_short_definition": "to work in \"short\" your deposit on the exchange must consist of the first currency in the trading pair",
        "grow_first_1_definition": "the first currency is selected, bot will accumulate",
        "grow_first_2_definition": "the second currency is selected, bot will accumulate",
        "dont_forget_to_save": "If you have made changes, save it by clicking the button \"Save settings\"",
        "timeframe_definition": "timeframe to be used in dynamic averaging strategy. The recommended values are \"5m-2h\"",
        "global_timeframe_definition": "global timeframe to be used in analysis by indicators. The recommended values are \"1h-8h\"",
        "ema200_delta_definition": "EMA200 length and EMA200 offset for FLAT trend identifying",
        "martingale_definition": "DCA/martingale. The coefficient of safety orders amount increase",
        "profit_definition": "one buy-sell cycle profit. The recommended volume is 0.4 - 2%",
        "buy_total_label": "Total number of orders",
        "buy_active_label": "Number of active SО",
        "sell_total_label": "Number of sell orders",
        "time_sleep_label": "Time sleep, sec./ coeff.",
        "time_sleep_definition": "pause between order status checks (set in seconds), as well as the pause multiplication factor (for cases when we searching entry the market and other cases where a short pause is not important)",
        "can_spend_second_currency_percent_definition": "the first currency deposit (%)",
        "can_spend_first_currency_percent_definition": "the second currency deposit (%)",
        "can_spend_second_currency_coin_definition": "the first currency deposit",
        "can_spend_first_currency_coin_definition": "the second currency deposit",
        "buy_total_definition": "the number of orders to be placed on the exchange",
        "first_step_definition": "the first order will be placed with the specified offset from the current price of the first currency in the pair",
        "lift_step_definition": "if the current price goes lower than the indent value, sell orders will be re-placed",
        "range_cover_definition": "the price difference, within which all orders will be placed",
        "co_range_cover_definition": "the indent value of the next averaging order price",
        "use_tf_switching_definition": "Use the timeframe switching function (with a rapid price change for more efficient averaging, the working timeframe will be switched to an increased one: from 5m to 15m, etc.)",
        "can_spend_label": "Deposit for",
        "bo_amount_label": "Basic order amount",
        "so_amount_label": "Safety orders amount",
        "leverage_label": "Leverage",
        "fix_manually": "Close manually",
        "one_or_more_label": "Orders placement mode*",
        "one_or_more_one_long_definition": "\"one\" option is selected: when the target buy price is reached, the next averaging buy order will be placed",
        "one_or_more_more_long_definition": "\"grid\" option is selected: averaging buy orders will be placed at the start and will wait for filling",
        "one_or_more_one_short_definition": "\"one\" option is selected: when the target sell price is reached, the next averaging sell order will be placed",
        "one_or_more_more_short_definition": "\"igrid\" option is selected: averaging sell orders will be placed at the start and will wait for filling",
        "one_order_label": "one_by_one",
        "more_order_label": "immediately",
        "api_key_secret_not_defined": "API KEY and API SECRET are not defined.\nEnter them in the config.toml",
        "invalid_number_format": "Invalid number format. Check all values.\nFloating-point numbers\nmust contain dot, not comma",
        "market_format_incorrect": "The market format is incorrect.\nPlease use the following trading market format:\nBTC/USDT, XVG/USDT..., etc.\nETH/BTC, DASH/BTC..., etc.\nETC/ETH, NEO/ETH..., etc.",
        "orders_total_incorrect": "The number of buy/sell orders is incorrect.\nThe minimum number is 2, the maximum is 50",
        "time_sleep_incorrect": "The time sleep is incorrect.\nThe minimum value is 0.5 sec., the maximum is 21600 sec.",
        "stoch_cci_incorrect": "Settings configuration is incorrect",
        "the_bot_stopped": "Fix order has been filled. The bot stopped",
        "sell_not_placed": "Sell order has not been placed. The bot stopped. Error:",
        "buy_not_placed": "Buy order has not been placed. The bot stopped. Error:",
        "log_stopped": "The bot stopped.",
        "log_error": "Error:",
        "waiting_for_balance": "Not enough balance. Waiting for sales from other bots or manual deposit",
        "no_balance": "There are no funds on the balance for averaging",
        "log_manual_averaging_ok": "ATTENTION! MANUAL AVERAGING HAS BEEN STARTED",
        "log_manual_sell_ok": "ATTENTION! THE MANUAL SALE OF COINS PREVIOUSLY BOUGHT BY THE BOT HAS BEEN LAUNCHED!",
        "log_manual_buy_ok": "ATTENTION! THE MANUAL BUY OF COINS PREVIOUSLY SOLD BY THE BOT HAS BEEN LAUNCHED!",
        "log_check_whitelist": "Check the whitelist of coins to add to the trade",
        "log_check_whitelist_ok": "Conditions have been found to start trade on a trading pair",
        "log_check_whitelist_add": "Adding to the list of base coins",
        "log_trend": "trend",
        "log_create_buy_macd_long": "Create buy order considering global trend",
        "log_create_buy_long": "Create buy order",
        "log_current_price": "Current price is",
        "log_liquidation_price": "Liquidation price is",
        "log_close_price": "Position closing price is",
        "log_previous_price": "Previous price was",
        "log_current_cci": "Current cci",
        "log_previous_cci": "Previous cci",
        "log_current_ma": "Current ma_1 и ma_2",
        "log_previous_ma": "Previous ma_1 and ma_2",
        "log_current_rsi": "Current rsi and smarsi",
        "log_previous_rsi": "Previous rsi and smarsi",
        "log_current_xxx": "Current",
        "log_previous_xxx": "Previous",
        "log_free_balance": "Your balance is",
        "log_free": "Free",
        "log_signal_found": "SIGNAL FOUND",
        "log_no_signal_yet": "There is no signal from",
        "log_for_closing": "to close",
        "log_closing_position": "CLOSING THE POSITION",
        "log_remaining_fix_value": "Fix order volume:",
        "log_remaining_remain": "Checking if fix-order is partially filled. Remaining:",
        "log_remaining_market_long": "A market order for the sale of the remaining is launched",
        "log_remaining_market_short": "A market order for the buy of the remaining is launched",
        "log_try_to_sell_remaining": "Trying to sell remaining",
        "log_try_to_buy_remaining": "Trying to buy remaining",
        "log_timeframe_switched": "AVERAGING TIMEFRAME HAS BEEN SWITCHED TO",
        "log_tf_switch_reason_ema_long": "The current price is below the global EMA",
        "log_tf_switch_reason_ema_short": "The current price is above the global EMA",
        "log_tf_switch_reason_order": "A trigger order has been placed",
        "log_tf_switch_reason_candle_long": "The market is falling too fast",
        "log_tf_switch_reason_candle_short": "The market is growing too fast",
        "log_tf_switch_reason_stoch": "of higher TF is in the averaging channel",
        "log_buy_price": "Buy price",
        "log_sell_price": "Sell price",
        "log_order_amount": "Order amount",
        "log_create_order": "create an order",
        "log_buy_order_created_long": "Buy order created",
        "log_failed_to_create":"Failed to create order",
        "log_failed_to_create_no_money": "Insufficient funds to place an order",
        "log_try_to_average_remaining_dep": "Trying to average using the remaining deposit",
        "log_total_spent_long": "Total for this trade was spent",
        "log_obtained": "obtained",
        "log_to_get_a_profit_long": "To get a profit, we need to sell the obtained currency at the rate",
        "log_after_fee": "Then after deducting the fee",
        "log_will_remain": "will remain the amount",
        "log_total_profit": "The total profit will be",
        "log_rate_for_sell_long": "The current rate for sell",
        "log_create_sell_rate_long": "Sell order will be filled at the rate",
        "log_create_sell_squeeze_rate_long": "Creating a squeeze-sell order at the rate",
        "log_create_stop_limit_long": "Set a limit order with a price",
        "log_profit": "profit",
        "log_more_sell_created_long": "several sell orders will be created, each with its own profit",
        "log_one_sell_created_long": "one sell order is created at the average purchase price of buy orders",
        "log_order_SELL_filled_short": "Filled BUY with amount",
        "log_order_filled_short": "Closed a SHORT position with amount",
        "log_order_STOP_filled_short": "STOP-loss filled. Closed a SHORT position with amount",
        "log_order_SQUEEZE_filled_short": "Filled a BUY-squeeze with amount",
        "log_order_STOP_canceled_short": "Canceled a BUY-squeeze order",
        "log_order_STOP_not_filled": "STOP is not filled yet. Waiting for price changes",
        "log_order_SQUEEZE_canceled_short": "Canceled a BUY-squeeze order with amount",
        "log_check_trend": "Current trends:",
        "log_current_trend": "TREND",
        "log_check_orders": "Check the status of orders",
        "log_check_total": "Total number of orders planned",
        "log_check_CO": "placed",
        "log_no_more_co": "No more orders to average your position :(",
        "log_avr_buy_price_is": "Entry price (long)",
        "log_avr_sell_price_is": "Entry price (short)",
        "log_no_more_co_telegram": "Attention! No more average orders for this pair",
        "log_order": "The order",
        "log_order_filled": "has already been filled!",
        "log_order_canceled": "was canceled!",
        "log_order_market_canceled_DB": "is marked as canceled in the DB",
        "log_order_with_amount": "order with amount",
        "log_unknown_pos_det": "A position placed by the user detected",
        "log_record_pos": "Recording the position data in the DB",
        "log_we_have_pos": "There is a position",
        "log_with_amount": "with amount",
        "log_order_with_price": "and price",
        "log_order_not_filled_yet": "is not filled yet",
        "log_order_SELL_filled_long": "Filled SELL with amount",
        "log_order_filled_long": "Closed a LONG position with amount",
        "log_order_STOP_filled_long": "STOP-loss filled. Closed a LONG position with amount",
        "log_order_SQUEEZE_filled_long": "Filled a LONG-squeeze with amount",
        "log_order_STOP_canceled_long": "Canceled a STOP-sell order",
        "log_order_SQUEEZE_canceled_long": "Canceled a LONG-squeeze with amount",
        "log_telegram": "send message to telegram",
        "log_filled_buy_sell_long": "For a filled buy order, we place a sell order",
        "log_max_buy_long": "The maximum price of buy order",
        "log_bid_price_long": "Bid price when bought",
        "log_time_remained": "The order will be canceled after: ",
        "log_time_min": "min.",
        "log_time_sec": "sec.",
        "log_current_trend_BULL": "The local EMA200 trend is BULLISH. Check if the trend has changed",
        "log_current_trend_changed_long": "The trend has changed, cancel buy orders",
        "log_current_trend_the_same": "The trend is the same. Orders cancellation is not necessary",
        "log_current_trend_FLAT": "The local EMA200 trend is \"FLAT\". Check if the trend has changed",
        "log_current_trend_BEAR": "The local EMA200 trend is BEARISH. Check if the trend has changed",
        "log_check_up_long": "Check if we need to move orders",
        "log_orders_up_long": "The price has risen, re-placing orders. CANCEL the order with amount",
        "log_orders_new_qfl": "New QFL base found. CANCEL the order with amount",
        "log_reversal_pattern_found": "A REVERSAL PATTERN HAS BEEN FOUND. WE BEGIN TO MONITOR",
        "log_with_qfl_base": "WITH THE BASE",
        "log_price_out_of_base": "THE PRICE WENT BEYOND THE FOUND BASE",
        "log_entry_with_algo": "ENTERING IN TO THE",
        "log_time_expired": "The orders life time has expired. Time to re-issue the orders",
        "log_filled_partially": "partially filled. Waiting for full filling",
        "log_no_orders": "There are no not filled orders in the DB, it's time to create new ones",
        "log_create_buys_long": "Create buy orders",
        "log_new_sell_created_long": "A new sell order is placed",
        "log_create_buy_macd_short": "Create sell order considering global trend",
        "log_create_buy_short": "Create sell order",
        "log_buy_order_created_short": "Sell order created",
        "log_total_spent_short": "Total for this trade was sold",
        "log_to_get_a_profit_short": "To get a profit, we need need to buy back the sold currency at the rate",
        "log_rate_for_sell_short": "The current rate for sell",
        "log_create_sell_rate_short": "Buy order will be filled at the rate",
        "log_create_sell_squeeze_rate_short": "Create a squeeze-buy order at the rate",
        "log_create_stop_limit_short": "Set a limit order with a price",
        "log_more_sell_created_short": "several buy orders will be created, each with its own profit",
        "log_one_sell_created_short": "one buy order is created at the average sell price of sell orders",
        "log_order_BUY_filled_short": "Filled a BUY order with amount",
        "log_filled_buy_sell_short": "For a filled sell order, we place a buy order",
        "log_min_buy_short": "The minimum price of sell order",
        "log_bid_price_short": "Ask price when sold",
        "log_current_trend_changed_short": "The trend has changed, cancel sell orders",
        "log_check_up_short": "Check if we need to move orders lower down",
        "log_orders_up_short": "The price has dropped, we are re-placing orders. CANCEL the order with amount",
        "log_create_buys_short": "Create sell orders",
        "log_new_sell_created_short": "A new buy order is placed",
        "log_initial_sell_price": "Initial sell order price",
        "log_initial_buy_price": "Initial buy order price",
        "log_5_days_from_BO": "The base order was filled more than 5 days ago. Check the bot",
        "log_order_squeeze_canceled_DB_long": "Squeeze order is cancelled, start trailing sell order",
        "log_order_squeeze_canceled_DB_short": "Squeeze order is cancelled, start trailing buy order",
        "log_order_stop_canceled_DB_long": "The price went up, cancel the existing trailing stop order",
        "log_order_stop_canceled_DB_short": "The price went down, cancel the existing trailing stop order",
        "log_create_stop": "Initiate a trailing stop order",
        "log_create_new_stop_long": "The price went up. Initiate a new stop order",
        "log_create_new_stop_short": "The price went down. Initiate a new stop order",
        "log_create_limit_stop_long": "The price went down. Filling a stop order at the limit price",
        "log_create_limit_stop_short": "The price went up. Filling a stop order at the limit price",
        "log_create_market_stop_long": "The price went down. Create a stop order at the current bid price",
        "log_create_market_stop_short": "The price went up. Create a stop order at the current ask price",
        "log_profit_price_long_is": "The profitable sale price is",
        "log_profit_price_short_is": "The profitable buy price is",
        "log_next_stop_price": "Trailing of the fix-order will be started when the price is reached",
        "log_stop_will_be_filled_at": "Stop order will be filled at the price",
        "log_if_price_went_down": "if it drops below",
        "log_if_price_went_up": "if it rises above",
        "log_next_avarage_sell_price": "The price of the next averaging sell order will be at least",
        "log_next_avarage_buy_price": "The price of the next averaging buy order will be no more than",
        "log_dynamic_on": "Dynamic averaging is enabled",
        "log_check_avarage_buy": "Check if it's time to place an averaging buy order",
        "log_check_avarage_sell": "Check if it's time to place an averaging sell order",
        "log_no_avarage": "It is too early to average, we expect price changes and indicator signals",
        "log_start_avarage_long": "The price went down. Check whether it is possible to average",
        "log_start_avarage_short": "The price went up. Check whether it is possible to average",
        "log_ema_global_allows_buy": "EMA_GLOBAL allows to place buy orders",
        "log_ema_global_allows_sell": "EMA_GLOBAL allows to place sell orders",
        "log_ema_global_allows": "EMA_GLOBAL does not recommend entering the market",
        "log_ema_entry_allows_buy": "EMA_ENTRY allows to place buy orders",
        "log_ema_entry_allows_sell": "EMA_ENTRY allows to place sell orders",
        "log_ema_entry_allows": "EMA_ENTRY does not recommend entering the market",
        "log_stoch_allows": "Рarameters of",
        "log_tv_allows_entry": "TradingView signal allows you to enter the market",
        "log_tv_allows_sell": "TradingView signal to exit the market has been received. We sell at the market price",
        "log_tv_allows_buy": "TradingView signal to exit the market has been received. We buy at the market price",
        "log_cross_sell": "signal has been received. We sell at the market price",
        "log_cross_buy": "signal has been received. We buy at the market price",
        "log_cci_cross_not_allows_entry": "ССI does not allow to enter the market",
        "log_cci_cross_allows_entry": "ССI allow to enter the market",
        "log_cci_cross_not_allows_avg": "ССI does not allow to average",
        "log_cci_cross_allows_avg": "ССI allow to average",
        "log_xxx_not_allows_avg": "not allow to average",
        "log_xxx_allows_avg": "allow to average",
        "log_cci_cross_not_allows_exit": "ССI does not allow to exit",
        "log_cci_cross_allows_exit": "ССI allow to exit",
        "log_stoch_not_allows": "does not recommend trading",
        "log_stoch_allows_exit": "allow to exit",
        "log_price_not_allows_exit": "does not allow to exit",
        "log_stoch_not_allows_exit": "or indicators doesn’t allow to exit",
        "log_waiting_for_price_long": "Waiting for the bid price more than",
        "log_waiting_for_price_short": "Waiting for ask price less than",
        "log_cci_allows": "CCI allows to entry into",
        "log_cci_not_allows": "CCI does not recommend trading",
        "log_rsi_allows": "RSI allows to entry into",
        "log_rsi_not_allows": "RSI does not recommend trading",
        "log_stoch_not_in_channel_long": "is not in channel yet. Waiting for the price decrease",
        "log_stoch_not_in_channel_short": "is not in channel yet. Waiting for the price increase",
        "log_good_margin_BO": "The price corresponds to the trading channel. Placing base order",
        "log_margin": "The trading channel is:",
        "log_margin_top": "top margin =",
        "log_margin_bottom": "bottom margin =",
        "log_good_margin": "The price corresponds to the trading channel. Trying to average",
        "log_bad_margin": "The price has gone beyond the trading channel border. Waiting for the price change",
        "log_exit_price_long": "Sell will start at a price of at least",
        "log_exit_price_short": "Buy will start at a price of no more than",
        "telegram_filled": "FILLED a",
        "telegram_from": "from",
        "telegram_bought": "BUY order of ",
        "telegram_stop_bought": "STOP-buy order of ",
        "telegram_squeeze_bought": "SQUEZZE-buy order of ",
        "telegram_stop_loss": "STOP-LOSS order of ",
        "telegram_stop_loss_filled": "Filled STOP-loss",
        "telegram_sold": "SELL order of",
        "telegram_stop_sold": "STOP-sell order of ",
        "telegram_squeeze_sold": "SQUEZZE-sell order of ",
        "telegram_for": "for",
        "telegram_placed": "placed a",
        "telegram_placed_buy": "BUY order of ",
        "telegram_placed_stop_buy": "STOP-buy order of ",
        "telegram_placed_squeeze_buy": "SQUEEZE-buy order of ",
        "telegram_placed_sell": "SELL order of ",
        "telegram_placed_stop_sell": "STOP-sell order of ",
        "telegram_placed_squeeze_sell": "SQUEEZE-sell order of ",
        "log_no_position": "There is no position. We check the conditions for entering the market",
        "log_no_conditions": "There are no entry conditions yet. Expect or adjust the settings",
        "telegram_close_position": "The position is closed",
        "telegram_deal_profit": "Deal profit",
        "trade_statistics": "Trade statistics",
        "statistics_long": "algorithm \"LONG\"",
        "statistics_bought_long": "Bought coins worth",
        "statistics_sold_long": "Sold coins worth",
        "statistics_if_will_sell_long": "If the bought coins will be sold, the profit will be",
        "statistics_or": "what is",
        "statistics_short": "algorithm \"SHORT\"",
        "statistics_sold_short": "Sold coins worth",
        "statistics_bought_short": "Bought back coins worth",
        "statistics_if_will_buy_short": "If the sold coins will be bougth back, the profit will be",
        "statistics_are_not_available": "Statistics not available yet",
        "test_buy_price": "price",
        "test_spent": "Spent",
        "orders_spent": "orders",
        "test_sell_price": "sell price",
        "test_fix_price": "fix order price",
        "test_sold": " sold",
        "test_received": "position size",
        "test_liquidation": "liquidation price",
        "test_price_increase": "price increase",
        "test_profit": "total profit",
        "test_delta": "difference",
        "test_profit_B": "Profit",
        "test_if_all_orders_filled": "If all orders will be filled, the total profit will be",
        "test_if_first_orders_filled": "If will be filled only the first",
        "test_orders_prifit_will_be": "orders, the total profit will be",
        "test_or": "or",
        "test_of_depo": "% of the deposit",
        "test_var_1": "If all orders will be filled:",
        "test_var_average_long": "The average buy price will be",
        "test_var_average_short": "The average sell price will be",
        "test_var_pnl": "The drawdown upon executing the last order will be",
        "test_var_liquidation": "Liquidation will occur before executing the last SO. Please review the settings and risks",
        "test_var_sell_price_long": "sell order will be placed at the price",
        "test_var_sell_price_short": "buy order will be placed at the price",
        "test_var_profit": "Total profit will be",
        "test_var_2": "Option 2 (If will be filled only the first",
        "test_var_orders": "orders)",
        "no_trend_change": "Looking for a turn point to average the position",
        "avr_order_level_was": "The averaging order level was",
        "price_delta": "Difference",
        "bo_price_delta": "Difference from basis order",
        "average_price_delta": "ROE",
        "average_position_price_delta": "Difference from average price",
        "bid_price": "Bid price",
        "fast_STOCH": "fast",
        "slow_STOCH": "slow",
        "log_exit_stop_loss_allows": "THE STOP LOSS WAS TRIGGERED. THE BOT IS FORCED TO FIX THE LOSS",
        "log_emergency_averaging": "EMERGENCY AVERAGING HAS BEEN LAUNCHED",
        "log_next_avr_for_manual": "Manual averaging will require",
        "trend_changes_avr_found": "The turn point was found",
        "trend_changes_avr_price_is": "Trying to make averaging by current price",
        "price_check": "Checking the price or indicators data",
        "price_go_up_long": "The price is higher than acceptable, averaging is not required",
        "price_go_down_short": "The price is lower than acceptable, averaging is not required",
        "stoch_fastk_period_label": "STOCH: %K, %D, slowdown",
        "stoch_fastk_period_definition": "the values of the fast curve, slow curve and slowdown for averaging on stochastic oscillator signal",
        "stoch_level_definition": "the levels of the stochastic oscillator, used for averaging in SHORT/LONG algorithms",
        "log_buy_string_found": "Buy string found in MAIL",
        "log_sell_string_found": "Sell string found in MAIL",
        "exit_timeframe_label": "Exit timeframe",
        "exit_use_tv_signals_label": "Use TradingView signal",
        "entry_use_stoch_or_cci_label": "Use STOCH / CCI",
        "avg_use_stoch_or_cci_label": "Use STOCH / CCI",
        "exit_use_stoch_or_cci_label": "Use STOCH / CCI",
        "entry_use_stoch_or_rsi_label": "Use STOCH / RSI",
        "avg_use_stoch_or_rsi_label": "Use STOCH / RSI",
        "exit_use_stoch_or_rsi_label": "Use STOCH / RSI",
        "exit_use_stoch_label": "Use STOCH signal",
        "exit_use_cci_label": "Use CCI signal",
        "exit_stoch_up_long_label": "Long STOCH (upper/lower)",
        "exit_stoch_up_short_label": "Short STOCH (upper/lower)",
        "exit_cci_level_label": "CCI exit level (short/long)",
        "exit_rsi_level_label": "RSI exit level (short/long)",
        "price_delta_label": "Close delta (short/long)",
        "avg_price_delta_label": "Last price delta (short/long)",
        "use_price_label": "Use price",
        "exit_timeframe_definition": "timeframe for determining indicators data when placing a take profit order",
        "exit_use_tv_signals_definition": "using TradingView signals and strategies for take profit",
        "exit_use_stoch_definition": "using stochastic oscillator for take profit",
        "exit_use_cci_definition": "using CCI for take profit",
        "exit_use_rsi_definition": "using RSI for take profit",
        "exit_stoch_level_definition": "stochastic oscillator levels used for take profit in SHORT/LONG algorithms",
        "exit_cci_level_definition": "CCI levels used for take profit in SHORT/LONG algorithms",
        "exit_rsi_level_definition": "RSI levels used for take profit in SHORT/LONG algorithms",
        "entry_by_indicators_label": "Use indicators to entry",
        "entry_timeframe_label": "Entry timeframe",
        "entry_preset_label": "Entry preset",
        "exit_preset_label": "Exit preset",
        "entry_basic_indicator_label": "Basic indicator",
        "avg_basic_indicator_label": "Basic indicator",
        "exit_basic_indicator_label": "Basic indicator",
        "exit_profit_level_label": "Profit / stop-loss, %",
        "entry_stoch_up_long_label": "Long STOCH (upper/lower)",
        "entry_stoch_up_short_label": "Short STOCH (upper/lower)",
        "entry_cci_level_label": "CCI entry (short/long)",
        "entry_rsi_level_label": "RSI entry (short/long)",
        "cci_cross_crossover": "Cross: from bottom to top",
        "cci_cross_crossunder": "Cross: from top to bottom",
        "qfl_N_label": "Candles before base",
        "qfl_M_label": "Candles after base",
        "1_qfl_h_l_percent_label": "Opening price indent, %",
        "2_qfl_h_l_percent_label": "Closing price indent, %",
        "ma1_cross_length_label": "MA_1 length",
        "ma2_cross_length_label": "MA_2 length",
        "rsi_level_long": "Long RSI (upper/lower)",
        "rsi_level_short": "Short RSI (upper/lower)",
        "smarsi_length_label": "SMA smoothing length",
        "stop_activated": "A simple stop loss is enabled. Monitoring the the price",
        "bo_global_stop_activated": "Stop loss is enabled for the base order. Monitoring the GLOBAL STOCH",
        "avg_use_tf_switching_label": "Use timeframe switch",
        "avg_timeframes_label": "Averaging timeframes",
        "avg_preset_label": "Averaging preset",
        "avg_stoch_up_long_label": "Long STOCH (upper/lower)",
        "avg_stoch_up_short_label": "Short STOCH (upper/lower)",
        "avg_cci_level_label": "CCI level (short/long)",
        "indicators_fine_tuning_label": "INDICATORS FINE TUNING",
        "timeframe_switching_label": "TIMEFRAME SWITCHING",
        "ema_global_switch_label": "EMA Global switch",
        "orders_switch_label": "Orders switch",
        "orders_count_label": "Number of orders",
        "last_candle_switch_label": "Last candles switch",
        "last_candle_count_label": "Number of candles",
        "stoch_adjustment_label": "STOCH adjustment, %",
        "miscellaneous_label": "MISCELLANEOUS",
        "immediate_so_label": "Place SO by market",
        "back_profit_label": "Profit reduction for TP, %",
        "so_safety_price_label": "Safety price for SO, %",
        "emergency_averaging_label": "Emergency averaging, %",
        "use_margin_label": "Use price corridor",
        "margin_top_and_bottom_label": "Top/bottom margin",
        "cancel_on_trend_label": "Cancel BO on trend changes",
        "use_stoch_rsi": "Use STOCH_RSI",
        "log_check_tf": "Сheck the timeframe entered in the configuration file. It seems that the exchange API does not support it",
        "log_stop_loss_price": "Stop loss trigger price:",
        "log_planning_stop_loss_price": "The planned stop loss trigger price:",
        "log_not_enough_bnb": "ATTENTION! NOT ENOUGH BNB ON YOUR BALANCE FOR COMMISSION FEE",
        "deal_duration": "Duration of the deal",
        "days": "d.",
        "hours": "hr.",
        "minutes": "min.",
        "seconds": "sec.",
        "log_entry_preset_chosen": "Entry preset chosen",
        "log_avg_preset_chosen": "Averaging preset chosen",
        "log_exit_preset_chosen": "Exit preset chosen",
        "log_global_stoch_allows_entry": "GLOBAL STOCH allows to enter the market",
        "log_global_stoch_not_allows_entry": "GLOBAL STOCH not allows to enter the market",
        "log_global_stoch_allows_avg": "GLOBAL STOCH allows to average",
        "log_global_stoch_allows_exit": "GLOBAL STOCH allows to exit",
    }
}
